ntrip_client:
  ros__parameters:
    host: "20.185.11.35"
    port: 2101
    mountpoint: "VRS_RTCM3"
    ntrip_version: "None"
    authenticate: true
    username: "user"
    password: "pass"
    ssl: false
    cert: "None"
    key: "None"
    ca_cert: "None"
    rtcm_message_package: "rtcm_msgs"
    rtcm_frame_id: "odom"
    nmea_max_length: 128
    nmea_min_length: 3
    reconnect_attempt_max: 10
    reconnect_attempt_wait_seconds: 5
    rtcm_timeout_seconds: 4